# Generated by Django 5.1.6 on 2025-04-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
