# Generated by Django 5.1.6 on 2025-04-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_postimage_description_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
